export interface Product {
    id: number;
    name: string;
    category: string;
    price: number;
    originalPrice: number;
    image: string;
    rating: number;
    reviews: number;
    discount: number;
    description: string;
    inStock: boolean;
}

export const mockProducts: Product[] = [
    {
        id: 1,
        name: 'Premium Wireless Headphones',
        category: 'Electronics',
        price: 79.99,
        originalPrice: 129.99,
        image: '/images/product-1.svg',
        rating: 4.8,
        reviews: 245,
        discount: 38,
        description: 'High-quality sound with noise cancellation',
        inStock: true,
    },
    {
        id: 2,
        name: 'Compact Earbuds Pro',
        category: 'Electronics',
        price: 49.99,
        originalPrice: 79.99,
        image: '/images/product-2.svg',
        rating: 4.5,
        reviews: 189,
        discount: 37,
        description: 'True wireless earbuds with extended battery',
        inStock: true,
    },
    {
        id: 3,
        name: '4K Webcam',
        category: 'Electronics',
        price: 99.99,
        originalPrice: 149.99,
        image: '/images/product-3.svg',
        rating: 4.6,
        reviews: 156,
        discount: 33,
        description: 'Crystal clear 4K video for streaming',
        inStock: true,
    },
    {
        id: 4,
        name: 'Mechanical Keyboard',
        category: 'Electronics',
        price: 89.99,
        originalPrice: 139.99,
        image: '/images/product-4.svg',
        rating: 4.7,
        reviews: 312,
        discount: 35,
        description: 'RGB backlit mechanical gaming keyboard',
        inStock: true,
    },
    {
        id: 5,
        name: 'Designer Sunglasses',
        category: 'Fashion',
        price: 59.99,
        originalPrice: 119.99,
        image: '/images/product-5.svg',
        rating: 4.4,
        reviews: 98,
        discount: 50,
        description: 'UV protection with stylish frames',
        inStock: true,
    },
    {
        id: 6,
        name: 'Athletic Shoes',
        category: 'Fashion',
        price: 69.99,
        originalPrice: 129.99,
        image: '/images/product-6.svg',
        rating: 4.6,
        reviews: 234,
        discount: 46,
        description: 'Comfortable cushioned sole for all-day wear',
        inStock: true,
    },
    {
        id: 7,
        name: 'Cotton T-Shirt',
        category: 'Fashion',
        price: 19.99,
        originalPrice: 34.99,
        image: '/images/product-7.svg',
        rating: 4.3,
        reviews: 156,
        discount: 43,
        description: '100% organic cotton, eco-friendly',
        inStock: true,
    },
    {
        id: 8,
        name: 'Classic Denim Jeans',
        category: 'Fashion',
        price: 49.99,
        originalPrice: 89.99,
        image: '/images/product-8.svg',
        rating: 4.5,
        reviews: 289,
        discount: 44,
        description: 'Premium denim with perfect fit',
        inStock: true,
    },
    {
        id: 9,
        name: 'Coffee Table',
        category: 'Home & Garden',
        price: 129.99,
        originalPrice: 199.99,
        image: '/images/product-9.svg',
        rating: 4.4,
        reviews: 76,
        discount: 35,
        description: 'Modern design with solid wood construction',
        inStock: true,
    },
    {
        id: 10,
        name: 'Desk Lamp',
        category: 'Home & Garden',
        price: 39.99,
        originalPrice: 69.99,
        image: '/images/product-10.svg',
        rating: 4.7,
        reviews: 124,
        discount: 43,
        description: 'LED lamp with adjustable brightness',
        inStock: true,
    },
    {
        id: 11,
        name: 'Throw Pillows Set',
        category: 'Home & Garden',
        price: 44.99,
        originalPrice: 79.99,
        image: '/images/product-11.svg',
        rating: 4.5,
        reviews: 89,
        discount: 44,
        description: 'Set of 2 decorative pillows',
        inStock: true,
    },
    {
        id: 12,
        name: 'Wall Clock',
        category: 'Home & Garden',
        price: 34.99,
        originalPrice: 59.99,
        image: '/images/product-12.svg',
        rating: 4.6,
        reviews: 102,
        discount: 42,
        description: 'Silent operation with modern design',
        inStock: true,
    },
    {
        id: 13,
        name: 'Yoga Mat',
        category: 'Sports',
        price: 29.99,
        originalPrice: 59.99,
        image: '/images/product-13.svg',
        rating: 4.5,
        reviews: 167,
        discount: 50,
        description: 'Non-slip cushioned yoga mat',
        inStock: true,
    },
    {
        id: 14,
        name: 'Dumbbells Set',
        category: 'Sports',
        price: 79.99,
        originalPrice: 149.99,
        image: '/images/product-14.svg',
        rating: 4.7,
        reviews: 234,
        discount: 47,
        description: '10-piece adjustable dumbbell set',
        inStock: true,
    },
    {
        id: 15,
        name: 'Running Shoes',
        category: 'Sports',
        price: 89.99,
        originalPrice: 159.99,
        image: '/images/product-15.svg',
        rating: 4.6,
        reviews: 198,
        discount: 44,
        description: 'Professional grade running shoes',
        inStock: true,
    },
    {
        id: 16,
        name: 'Fitness Tracker',
        category: 'Sports',
        price: 59.99,
        originalPrice: 129.99,
        image: '/images/product-16.svg',
        rating: 4.4,
        reviews: 145,
        discount: 54,
        description: 'Monitor heart rate and daily activity',
        inStock: true,
    },
    {
        id: 17,
        name: 'The Great Gatsby',
        category: 'Books',
        price: 12.99,
        originalPrice: 18.99,
        image: '/images/product-17.svg',
        rating: 4.8,
        reviews: 512,
        discount: 32,
        description: 'Classic American novel',
        inStock: true,
    },
    {
        id: 18,
        name: 'Clean Code',
        category: 'Books',
        price: 34.99,
        originalPrice: 49.99,
        image: '/images/product-18.svg',
        rating: 4.7,
        reviews: 456,
        discount: 30,
        description: 'A Handbook of Agile Software Craftsmanship',
        inStock: true,
    },
    {
        id: 19,
        name: 'Atomic Habits',
        category: 'Books',
        price: 16.99,
        originalPrice: 24.99,
        image: '/images/product-19.svg',
        rating: 4.9,
        reviews: 678,
        discount: 32,
        description: 'Build better habits with tiny changes',
        inStock: true,
    },
    {
        id: 20,
        name: 'Design Patterns',
        category: 'Books',
        price: 44.99,
        originalPrice: 64.99,
        image: '/images/product-20.svg',
        rating: 4.6,
        reviews: 234,
        discount: 31,
        description: 'Elements of Reusable Object-Oriented Software',
        inStock: true,
    },
];
