export interface Product {
    id: number;
    name: string;
    category: string;
    price: number;
    originalPrice: number;
    image: string;
    rating: number;
    reviews: number;
    discount: number;
    description: string;
    inStock: boolean;
}

export const mockProducts: Product[] = [
    {
        id: 1,
        name: 'AirWave True Wireless Earbuds',
        category: 'Audio',
        price: 79.99,
        originalPrice: 129.99,
        image: '/images/product-1.svg',
        rating: 4.8,
        reviews: 245,
        discount: 38,
        description: 'Immersive sound with adaptive noise isolation and long battery life.',
        inStock: true,
    },
    {
        id: 2,
        name: 'ZenCharge Fast Wireless Pad',
        category: 'Chargers',
        price: 49.99,
        originalPrice: 79.99,
        image: '/images/product-2.svg',
        rating: 4.5,
        reviews: 189,
        discount: 37,
        description: 'Fast charging pad for Qi-enabled phones with a compact design.',
        inStock: true,
    },
    {
        id: 3,
        name: 'GuardPro Leather Phone Case',
        category: 'Cases',
        price: 34.99,
        originalPrice: 59.99,
        image: '/images/product-3.svg',
        rating: 4.6,
        reviews: 156,
        discount: 41,
        description: 'Slim, premium leather case with drop protection and grip texture.',
        inStock: true,
    },
    {
        id: 4,
        name: 'MagMount Magnetic Car Holder',
        category: 'Mounts',
        price: 24.99,
        originalPrice: 44.99,
        image: '/images/product-4.svg',
        rating: 4.7,
        reviews: 312,
        discount: 44,
        description: 'Secure magnetic phone mount with 360° rotation for in-car navigation.',
        inStock: true,
    },
    {
        id: 5,
        name: 'VividShield Tempered Glass',
        category: 'Protectors',
        price: 19.99,
        originalPrice: 34.99,
        image: '/images/product-5.svg',
        rating: 4.4,
        reviews: 98,
        discount: 43,
        description: 'Ultra-clear screen protection with anti-scratch coating.',
        inStock: true,
    },
    {
        id: 6,
        name: 'CablePro USB-C Fast Charge',
        category: 'Cables',
        price: 15.99,
        originalPrice: 29.99,
        image: '/images/product-6.svg',
        rating: 4.6,
        reviews: 234,
        discount: 47,
        description: 'Durable braided cable for fast charging and data transfer.',
        inStock: true,
    },
    {
        id: 7,
        name: 'PopGrip Slide Stand',
        category: 'Accessories',
        price: 12.99,
        originalPrice: 24.99,
        image: '/images/product-7.svg',
        rating: 4.3,
        reviews: 156,
        discount: 48,
        description: 'Ergonomic phone grip and stand for hands-free viewing.',
        inStock: true,
    },
    {
        id: 8,
        name: 'NovaScreen Privacy Filter',
        category: 'Protectors',
        price: 29.99,
        originalPrice: 49.99,
        image: '/images/product-8.svg',
        rating: 4.5,
        reviews: 289,
        discount: 40,
        description: 'Privacy screen protector that keeps your display secure from side views.',
        inStock: true,
    },
    {
        id: 9,
        name: 'ChargeStation 20K Power Bank',
        category: 'Power Banks',
        price: 69.99,
        originalPrice: 109.99,
        image: '/images/product-9.svg',
        rating: 4.4,
        reviews: 76,
        discount: 36,
        description: 'High-capacity portable battery with fast PD charging output.',
        inStock: true,
    },
    {
        id: 10,
        name: 'AuraAir Bluetooth Speaker',
        category: 'Audio',
        price: 39.99,
        originalPrice: 69.99,
        image: '/images/product-10.svg',
        rating: 4.7,
        reviews: 124,
        discount: 43,
        description: 'Compact Bluetooth speaker with rich sound and bass boost.',
        inStock: true,
    },
    {
        id: 11,
        name: 'FlexMount Bike Phone Holder',
        category: 'Mounts',
        price: 34.99,
        originalPrice: 59.99,
        image: '/images/product-11.svg',
        rating: 4.5,
        reviews: 89,
        discount: 44,
        description: 'Adjustable phone holder for bike handlebars with secure grip.',
        inStock: true,
    },
    {
        id: 12,
        name: 'TravelCharge Multi Adapter',
        category: 'Chargers',
        price: 24.99,
        originalPrice: 44.99,
        image: '/images/product-12.svg',
        rating: 4.6,
        reviews: 102,
        discount: 43,
        description: 'Universal travel adapter with USB-C and USB-A ports.',
        inStock: true,
    },
    {
        id: 13,
        name: 'NeoBrace Sport Band',
        category: 'Wearables',
        price: 29.99,
        originalPrice: 59.99,
        image: '/images/product-13.svg',
        rating: 4.5,
        reviews: 167,
        discount: 50,
        description: 'Comfortable smartwatch band for active all-day wear.',
        inStock: true,
    },
    {
        id: 14,
        name: 'ChargeDock Wireless Stand',
        category: 'Chargers',
        price: 54.99,
        originalPrice: 89.99,
        image: '/images/product-14.svg',
        rating: 4.7,
        reviews: 234,
        discount: 39,
        description: 'Vertical wireless charging stand for desk or nightstand.',
        inStock: true,
    },
    {
        id: 15,
        name: 'ArmorShell Rugged Case',
        category: 'Cases',
        price: 44.99,
        originalPrice: 79.99,
        image: '/images/product-15.svg',
        rating: 4.6,
        reviews: 198,
        discount: 43,
        description: 'Heavy-duty protective case with drop absorption technology.',
        inStock: true,
    },
    {
        id: 16,
        name: 'SmartCharge USB-C Hub',
        category: 'Cables',
        price: 59.99,
        originalPrice: 99.99,
        image: '/images/product-16.svg',
        rating: 4.4,
        reviews: 145,
        discount: 40,
        description: 'Multiport USB-C hub for high-speed charging and data transfer.',
        inStock: true,
    },
    {
        id: 17,
        name: 'FreshSound Neckband Earphones',
        category: 'Audio',
        price: 29.99,
        originalPrice: 49.99,
        image: '/images/product-17.svg',
        rating: 4.8,
        reviews: 512,
        discount: 40,
        description: 'Lightweight neckband earphones with crisp audio and long battery life.',
        inStock: true,
    },
    {
        id: 18,
        name: 'PixelGrip Gaming Phone Handle',
        category: 'Accessories',
        price: 34.99,
        originalPrice: 59.99,
        image: '/images/product-18.svg',
        rating: 4.7,
        reviews: 456,
        discount: 42,
        description: 'Ergonomic phone grip made for mobile gaming and streaming.',
        inStock: true,
    },
    {
        id: 19,
        name: 'OptiLens Clip-On Camera Kit',
        category: 'Accessories',
        price: 16.99,
        originalPrice: 24.99,
        image: '/images/product-19.svg',
        rating: 4.9,
        reviews: 678,
        discount: 32,
        description: 'Clip-on lenses for sharper mobile photography on the go.',
        inStock: true,
    },
    {
        id: 20,
        name: 'MobileCare Cleaning Kit',
        category: 'Accessories',
        price: 14.99,
        originalPrice: 24.99,
        image: '/images/product-20.svg',
        rating: 4.6,
        reviews: 234,
        discount: 37,
        description: 'Complete cleaning kit for screens, ports, and phone cases.',
        inStock: true,
    },
];
